"""empty message

Revision ID: b9f6f9f5becc
Revises: 9b70402c7a54
Create Date: 2024-08-09 14:19:48.006576

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b9f6f9f5becc"
down_revision = "9b70402c7a54"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("recipe_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("review", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            "fk_reviews_recipe_id", "recipes", ["recipe_id"], ["id"]
        )
        batch_op.create_foreign_key("fk_reviews_user_id", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("review")
        batch_op.drop_column("recipe_id")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
